In [1]:
# Import libraries
import numpy as np
import pandas as pd

In [2]:
# Read in the trip summary data
file_path = '../data/trip_summary_201901.csv'
trips = pd.read_csv(file_path)
trips

start_date  start_hour  start_station_id  \
0       2019-01-01           0               109   
1       2019-01-01           0               109   
2       2019-01-01           0               118   
3       2019-01-01           0               119   
4       2019-01-01           0               120   
5       2019-01-01           0               121   
6       2019-01-01           0                13   
7       2019-01-01           0                13   
8       2019-01-01           0               138   
9       2019-01-01           0                15   
10      2019-01-01           0                15   
11      2019-01-01           0                16   
12      2019-01-01           0                16   
13      2019-01-01           0               163   
14      2019-01-01           0               182   
15      2019-01-01           0               193   
16      2019-01-01           0               196   
17      2019-01-01           0                20   
18      2019-01-01           0                20   
19      2019-01-01           0                21   
20      2019-01-01           0                21   
21      2019-01-01           0                21   
22      2019-01-01           0                21   
23      2019-01-01           0               211   
24      2019-01-01           0                23   
25      2019-01-01           0                23   
26      2019-01-01           0                23   
27      2019-01-01           0                23   
28      2019-01-01           0                23   
29      2019-01-01           0                23   
...            ...         ...               ...   
167047  2019-01-31          23               311   
167048  2019-01-31          23               318   
167049  2019-01-31          23                34   
167050  2019-01-31          23               349   
167051  2019-01-31          23               364   
167052  2019-01-31          23               364   
167053  2019-01-31          23               364   
167054  2019-01-31          23               370   
167055  2019-01-31          23               370   
167056  2019-01-31          23               378   
167057  2019-01-31          23               385   
167058  2019-01-31          23                41   
167059  2019-01-31          23                47   
167060  2019-01-31          23                47   
167061  2019-01-31          23                47   
167062  2019-01-31          23                54   
167063  2019-01-31          23                67   
167064  2019-01-31          23                73   
167065  2019-01-31          23                74   
167066  2019-01-31          23                75   
167067  2019-01-31          23                77   
167068  2019-01-31          23                78   
167069  2019-01-31          23                81   
167070  2019-01-31          23                86   
167071  2019-01-31          23                86   
167072  2019-01-31          23                87   
167073  2019-01-31          23                87   
167074  2019-01-31          23                89   
167075  2019-01-31          23                95   
167076  2019-01-31          23                99   

                                       start_station_name  start_station_cap  \
0                                  17th St at Valencia St               23.0   
1                                  17th St at Valencia St               23.0   
2                         Eureka Valley Recreation Center               19.0   
3                                       18th St at Noe St               15.0   
4                                    Mission Dolores Park               27.0   
5                                      Mission Playground               23.0   
6                          Commercial St at Montgomery St               23.0   
7                          Commercial St at Montgomery St               23.0   
8                                  Jersey St at Church St      

In [61]:
# create station pair identifiers and group the data

# Function: sorts the pair array and concatenates them to create a unique ID
def sort_concat(arr):
    arr_sorted = np.sort(arr)
    pair_id = str(arr_sorted[0]) + '_' + str(arr_sorted[1])
    
    return pair_id

pair_id = trips[['start_station_id', 'end_station_id']].values
pair_id_sorted = list(map(sort_concat, pair_id))

trips['station_pair_id'] = pair_id_sorted
trips

start_date  start_hour  start_station_id  \
0       2019-01-01           0               109   
1       2019-01-01           0               109   
2       2019-01-01           0               118   
3       2019-01-01           0               119   
4       2019-01-01           0               120   
5       2019-01-01           0               121   
6       2019-01-01           0                13   
7       2019-01-01           0                13   
8       2019-01-01           0               138   
9       2019-01-01           0                15   
10      2019-01-01           0                15   
11      2019-01-01           0                16   
12      2019-01-01           0                16   
13      2019-01-01           0               163   
14      2019-01-01           0               182   
15      2019-01-01           0               193   
16      2019-01-01           0               196   
17      2019-01-01           0                20   
18      2019-01-01           0                20   
19      2019-01-01           0                21   
20      2019-01-01           0                21   
21      2019-01-01           0                21   
22      2019-01-01           0                21   
23      2019-01-01           0               211   
24      2019-01-01           0                23   
25      2019-01-01           0                23   
26      2019-01-01           0                23   
27      2019-01-01           0                23   
28      2019-01-01           0                23   
29      2019-01-01           0                23   
...            ...         ...               ...   
167047  2019-01-31          23               311   
167048  2019-01-31          23               318   
167049  2019-01-31          23                34   
167050  2019-01-31          23               349   
167051  2019-01-31          23               364   
167052  2019-01-31          23               364   
167053  2019-01-31          23               364   
167054  2019-01-31          23               370   
167055  2019-01-31          23               370   
167056  2019-01-31          23               378   
167057  2019-01-31          23               385   
167058  2019-01-31          23                41   
167059  2019-01-31          23                47   
167060  2019-01-31          23                47   
167061  2019-01-31          23                47   
167062  2019-01-31          23                54   
167063  2019-01-31          23                67   
167064  2019-01-31          23                73   
167065  2019-01-31          23                74   
167066  2019-01-31          23                75   
167067  2019-01-31          23                77   
167068  2019-01-31          23                78   
167069  2019-01-31          23                81   
167070  2019-01-31          23                86   
167071  2019-01-31          23                86   
167072  2019-01-31          23                87   
167073  2019-01-31          23                87   
167074  2019-01-31          23                89   
167075  2019-01-31          23                95   
167076  2019-01-31          23                99   

                                       start_station_name  start_station_cap  \
0                                  17th St at Valencia St               23.0   
1                                  17th St at Valencia St               23.0   
2                         Eureka Valley Recreation Center               19.0   
3                                       18th St at Noe St               15.0   
4                                    Mission Dolores Park               27.0   
5                                      Mission Playground               23.0   
6                          Commercial St at Montgomery St               23.0   
7                          Commercial St at Montgomery St               23.0   
8                                  Jersey St at Church St      

In [114]:
# Create an affinity matrix from the data
pair_trips = trips.groupby('station_pair_id', as_index=False)['trip_count'].sum()
pair_trips['station_i'] = pair_trips['station_pair_id'].str.split("_", n = 1, expand = True)[0]
pair_trips['station_j'] = pair_trips['station_pair_id'].str.split("_", n = 1, expand = True)[1]
pair_trips['trip_count_inv'] = 1 / pair_trips['trip_count']
print(pair_trips.head())

# Generate affinity matrix from pair_trips
upp_mat = pair_trips.set_index(['station_i','station_j'])['trip_count_inv'].unstack().values
print(upp_mat)

aff_mat = np.triu(upp_mat) + np.triu(upp_mat, 1).T
aff_mat[np.isnan(aff_mat)] = 0

print(aff_mat)

  station_pair_id  trip_count station_i station_j  trip_count_inv
0         100_100           8       100       100        0.125000
1         100_101           7       100       101        0.142857
2         100_102           9       100       102        0.111111
3         100_104          11       100       104        0.090909
4         100_105           6       100       105        0.166667
[[0.03030303        nan        nan ... 0.33333333 0.33333333 0.33333333]
 [       nan 0.125      0.14285714 ...        nan        nan        nan]
 [       nan        nan 0.25       ...        nan        nan        nan]
 ...
 [       nan 0.08333333 0.09090909 ... 0.05       0.05       0.16666667]
 [       nan 0.08333333 0.09090909 ...        nan 0.2        0.16666667]
 [       nan 0.08333333 0.5        ...        nan        nan 0.14285714]]
[[0.03030303 0.         0.         ... 0.33333333 0.33333333 0.33333333]
 [0.         0.125      0.14285714 ... 0.         0.         0.        ]
 [0.         0

In [116]:
# Spectral clustering on the affinity matrix
from sklearn.cluster import SpectralClustering

beta = 1
sim_mat = np.exp(-beta * aff_mat / aff_mat.std(ddof=0))
print(sim_mat)

sc = SpectralClustering(3, affinity='precomputed', n_init=100, assign_labels='discretize')
sc.fit_predict(sim_mat)

[[0.85873748 1.         1.         ... 0.18726845 0.18726845 0.18726845]
 [1.         0.5335489  0.48775207 ... 1.         1.         1.        ]
 [1.         0.48775207 0.28467443 ... 1.         1.         1.        ]
 ...
 [0.18726845 1.         1.         ... 0.77780314 0.77780314 0.43274525]
 [0.18726845 1.         1.         ... 0.77780314 0.36599805 0.43274525]
 [0.18726845 1.         1.         ... 0.43274525 0.43274525 0.48775207]]


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0,
       0, 2, 0, 1, 2, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 1, 1, 1,
       1, 0, 2, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       2, 1, 1, 1, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 0, 1, 1, 1, 1, 2, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 2, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 2, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 2, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 1, 2, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0,