In [1]:
# Import libraries
import numpy as np
import pandas as pd

In [29]:
# Read in the trip summary data
file_path = '../data/trip_summary_201901.csv'
trips = pd.read_csv(file_path)
trips = trips.dropna(how="any")

trips['start_station_id'].nunique()

152

In [30]:
# Create station pair identifiers and group the data

# Function: sorts the pair array and concatenates them to create a unique ID
def sort_concat(arr):
    arr_sorted = np.sort(arr)
    pair_id = str(arr_sorted[0]) + '_' + str(arr_sorted[1])
    
    return pair_id

pair_id = trips[['start_station_id', 'end_station_id']].values
pair_id_sorted = list(map(sort_concat, pair_id))

trips['station_pair_id'] = pair_id_sorted
trips

start_date  start_hour  start_station_id  \
0       2019-01-01           0               109   
1       2019-01-01           0               109   
2       2019-01-01           0               118   
3       2019-01-01           0               119   
4       2019-01-01           0               120   
5       2019-01-01           0               121   
6       2019-01-01           0                13   
7       2019-01-01           0                13   
8       2019-01-01           0               138   
9       2019-01-01           0                15   
10      2019-01-01           0                15   
11      2019-01-01           0                16   
12      2019-01-01           0                16   
17      2019-01-01           0                20   
18      2019-01-01           0                20   
19      2019-01-01           0                21   
20      2019-01-01           0                21   
21      2019-01-01           0                21   
22      2019-01-01           0                21   
24      2019-01-01           0                23   
25      2019-01-01           0                23   
26      2019-01-01           0                23   
27      2019-01-01           0                23   
28      2019-01-01           0                23   
29      2019-01-01           0                23   
30      2019-01-01           0                23   
31      2019-01-01           0                24   
32      2019-01-01           0                24   
36      2019-01-01           0                27   
37      2019-01-01           0                28   
...            ...         ...               ...   
167039  2019-01-31          23                28   
167040  2019-01-31          23                29   
167041  2019-01-31          23                29   
167042  2019-01-31          23                 3   
167049  2019-01-31          23                34   
167050  2019-01-31          23               349   
167051  2019-01-31          23               364   
167052  2019-01-31          23               364   
167053  2019-01-31          23               364   
167054  2019-01-31          23               370   
167055  2019-01-31          23               370   
167058  2019-01-31          23                41   
167059  2019-01-31          23                47   
167060  2019-01-31          23                47   
167061  2019-01-31          23                47   
167062  2019-01-31          23                54   
167063  2019-01-31          23                67   
167064  2019-01-31          23                73   
167065  2019-01-31          23                74   
167066  2019-01-31          23                75   
167067  2019-01-31          23                77   
167068  2019-01-31          23                78   
167069  2019-01-31          23                81   
167070  2019-01-31          23                86   
167071  2019-01-31          23                86   
167072  2019-01-31          23                87   
167073  2019-01-31          23                87   
167074  2019-01-31          23                89   
167075  2019-01-31          23                95   
167076  2019-01-31          23                99   

                                       start_station_name  start_station_cap  \
0                                  17th St at Valencia St               23.0   
1                                  17th St at Valencia St               23.0   
2                         Eureka Valley Recreation Center               19.0   
3                                       18th St at Noe St               15.0   
4                                    Mission Dolores Park               27.0   
5                                      Mission Playground               23.0   
6                          Commercial St at Montgomery St               23.0   
7                          Commercial St at Montgomery St               23.0   
8                                  Jersey St at Church St      

In [62]:
# Create an affinity matrix from the data
pair_trips = trips.groupby('station_pair_id', as_index=False)['trip_count'].sum()
pair_trips['station_i'] = pair_trips['station_pair_id'].str.split("_", n = 1, expand = True)[0]
pair_trips['station_j'] = pair_trips['station_pair_id'].str.split("_", n = 1, expand = True)[1]
pair_trips['trip_count_inv'] = 1 / pair_trips['trip_count']

pair_trips['station_i'] = pd.to_numeric(pair_trips['station_i']).astype(np.int64)
pair_trips['station_j'] = pd.to_numeric(pair_trips['station_j']).astype(np.int64)

stations_sorted = pair_trips.sort_values(['station_i'])['station_i'].unique()
pair_trips = pair_trips.sort_values(['station_i'])

print(stations_sorted,"\n")
print(len(stations_sorted),"\n")
print(pair_trips.head(), "\n")

# Generate affinity matrix from pair_trips
upp_mat = pair_trips.set_index(['station_i','station_j'])['trip_count_inv'].unstack().values

aff_mat = np.triu(upp_mat) + np.triu(upp_mat, 1).T
aff_mat[np.isnan(aff_mat)] = 0

print(aff_mat, "\n")
print(aff_mat.shape)

[  3   4   5   6   8   9  10  11  13  14  15  16  17  19  20  21  22  23
  24  25  26  27  28  29  30  31  33  34  36  37  39  41  42  43  44  47
  49  50  52  53  54  55  56  58  59  60  61  62  63  64  66  67  70  71
  72  73  74  75  76  77  78  79  80  81  84  85  86  87  88  89  90  91
  92  93  95  96  97  98  99 100 101 102 104 105 106 107 108 109 110 112
 113 114 115 116 118 119 120 121 122 123 124 125 126 127 129 130 131 132
 133 134 136 137 138 139 140 141 142 144 145 146 147 223 284 285 321 323
 324 336 343 345 349 350 355 356 358 359 360 361 362 363 364 365 368 369
 370 371 373 375 377 380 381 383] 

152 

     station_pair_id  trip_count  station_i  station_j  trip_count_inv
5014           3_350          61          3        350        0.016393
5036            3_39          14          3         39        0.071429
5037             3_4          17          3          4        0.058824
5038            3_41          51          3         41        0.019608
5039            3_4

In [63]:
# Spectral clustering on the affinity matrix
from sklearn.cluster import SpectralClustering

beta = 1
sim_mat = np.exp(-beta * aff_mat / aff_mat.std(ddof=0))
print(sim_mat)

sc = SpectralClustering(3, affinity='precomputed', n_init=100, assign_labels='discretize')
clusters = sc.fit_predict(sim_mat)
print(len(clusters))

[[0.94702883 0.82259411 0.96916493 ... 0.71748944 0.0361539  0.73947449]
 [0.82259411 0.5147911  0.88818931 ... 0.33066258 0.0361539  0.62233205]
 [0.96916493 0.88818931 0.94944798 ... 0.78888025 0.0361539  0.69150451]
 ...
 [0.71748944 0.33066258 0.78888025 ... 0.81261474 1.         0.0361539 ]
 [0.0361539  0.0361539  0.0361539  ... 1.         0.62233205 0.0361539 ]
 [0.73947449 0.62233205 0.69150451 ... 0.0361539  0.0361539  0.0361539 ]]
152


In [64]:
clusters

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 1,
       2, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 1, 0, 0,
       0, 0, 2, 2, 1, 0, 1, 1, 0, 0, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 1, 2, 2, 2, 1, 0, 2, 2,
       2, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1,
       2, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 1, 1, 1, 0, 0, 0, 0, 0, 2],
      dtype=int64)

In [67]:
list(zip(stations_sorted, clusters))

[(3, 1),
 (4, 1),
 (5, 1),
 (6, 1),
 (8, 0),
 (9, 1),
 (10, 1),
 (11, 1),
 (13, 1),
 (14, 1),
 (15, 1),
 (16, 1),
 (17, 1),
 (19, 1),
 (20, 1),
 (21, 1),
 (22, 1),
 (23, 1),
 (24, 1),
 (25, 1),
 (26, 1),
 (27, 1),
 (28, 1),
 (29, 0),
 (30, 1),
 (31, 0),
 (33, 0),
 (34, 0),
 (36, 1),
 (37, 1),
 (39, 2),
 (41, 1),
 (42, 1),
 (43, 0),
 (44, 1),
 (47, 1),
 (49, 1),
 (50, 1),
 (52, 0),
 (53, 0),
 (54, 0),
 (55, 0),
 (56, 2),
 (58, 1),
 (59, 2),
 (60, 1),
 (61, 1),
 (62, 1),
 (63, 0),
 (64, 1),
 (66, 1),
 (67, 1),
 (70, 0),
 (71, 0),
 (72, 0),
 (73, 0),
 (74, 0),
 (75, 0),
 (76, 0),
 (77, 2),
 (78, 0),
 (79, 1),
 (80, 2),
 (81, 1),
 (84, 0),
 (85, 0),
 (86, 0),
 (87, 0),
 (88, 2),
 (89, 2),
 (90, 1),
 (91, 0),
 (92, 1),
 (93, 1),
 (95, 0),
 (96, 0),
 (97, 2),
 (98, 2),
 (99, 0),
 (100, 2),
 (101, 1),
 (102, 0),
 (104, 2),
 (105, 0),
 (106, 2),
 (107, 2),
 (108, 2),
 (109, 2),
 (110, 2),
 (112, 2),
 (113, 2),
 (114, 2),
 (115, 2),
 (116, 2),
 (118, 0),
 (119, 2),
 (120, 0),
 (121, 2),
 (122, 